# Default values for tika-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: bitnami/tika-server
  tag: 1.14
  pullPolicy: IfNotPresent
tika:
  version: 1.14
  translator: 
    google:
      clientsecret: PUT_YOUR_KEY_HERE
service:
  name: tika
  type: ClusterIP
  externalPort: 80
  internalPort: 9998
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

